package com.seeewo4kin.bot.Enums;

public enum UserState {
    START,
    CAPTCHA_CHECK,
    MAIN_MENU,
    BUY_MENU,
    SELL_MENU,
    OTHER_MENU,
    ENTERING_BUY_AMOUNT_RUB,
    ENTERING_BUY_AMOUNT_BTC,
    ENTERING_SELL_AMOUNT,
    APPLYING_COUPON,
    VIEWING_APPLICATIONS,
    VIEWING_COUPONS,
    REFERRAL_MENU,
    CREATING_REFERRAL_CODE,
    ENTERING_REFERRAL_CODE,
    CONFIRMING_VIP,
    ENTERING_WALLET,
    // Админские состояния
    ADMIN_MAIN_MENU,
    ADMIN_VIEWING_ALL_APPLICATIONS,
    ADMIN_VIEWING_APPLICATION_DETAILS,
    ADMIN_COMMISSION_SETTINGS
}